### ISSUE TITLE
对长句支持不佳

### ISSUE THREAD

**Issue by wzyddg** [lsj9383/translate-set#1]
我在GoogleDispatch类的私有构造函数GoogleDispatch()里加了一句langMap.put("ru", "ru");来翻译俄语，效果喜人，但是在遇到长句的时候，抛出了异常如下：
Exception in thread "main" net.sf.json.JSONException: A JSONArray text must start with '[' at character 1 of <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>
	at net.sf.json.util.JSONTokener.syntaxError(JSONTokener.java:499)
	at net.sf.json.JSONArray._fromJSONTokener(JSONArray.java:1116)
	at net.sf.json.JSONArray._fromString(JSONArray.java:1197)
	at net.sf.json.JSONArray.fromObject(JSONArray.java:127)
	at net.sf.json.JSONArray.fromObject(JSONArray.java:105)
	at com.lsj.trans.GoogleDispatch.ParseString(GoogleDispatch.java:69)
	at com.lsj.trans.GoogleDispatch.Trans(GoogleDispatch.java:64)

我觉得是返回的网页 报错所以解析失败。

我用的例句：
        <text>Внатуре, спасибо тебе, братан. Короче, приходил сюда один такой сталкер, ну... мы с ним ничего не делали, честно. Он спустился к нам на базу к трубам вниз, так тут откуда-то кровосос взялся, да напал на наших людей, уволок двоих туда в логово двоих, включая его. Братана моего покоцало, я его сюда вытащил, кровь никак не остановить. Если ищешь его, спускайся вниз, только будь осторожен, опасайся той твари.</text>

**Comment by lsj9383** [comment]
您好，请问问题是否已经解决？在我的环境下并无问题。（您的例句转中文还是转英文都是可以的）
我的运行ide是:
```
Eclipse IDE for Java Developers

Version: Neon.1a Release (4.6.1)
```
如果您的工程还有问题并亟待解决，可以将您的工程文件发送至99449107@qq.com，我尝试帮您解决。

**Comment by wzyddg** [comment]
没有解决
我的环境：
Eclipse Java EE IDE for Web Developers.
Version: Neon.1a Release (4.6.1)

java version "1.8.0_77"

其他java项目都可以正常跑。
我只在GoogleDispatch()里加了langMap.put("ru", "ru");在Main类main函数里的TransInit();之后调用
System.out.println(Dispatch.Instance("google").Trans("ru", "zh", "Внатуре, спасибо тебе, братан. Короче, приходил сюда один такой сталкер, ну... мы с ним ничего не делали, честно. Он спустился к нам на базу к трубам вниз, так тут откуда-то кровосос взялся, да напал на наших людей, уволок двоих туда в логово двоих, включая его. Братана моего покоцало, я его сюда вытащил, кровь никак не остановить. Если ищешь его, спускайся вниз, только будь осторожен, опасайся той твари."));

其他都没有改动过了，我在我的windows电脑和mac上都试过，相同异常。
改用百度的翻译就可以成功。

**Comment by lsj9383** [comment]
您好，在您的工程里面，GoogleDispatch.Trans方法中，应该会判断字符长度然后选择get或是post的方式发送参数，请将这个地方修改为不作判断，始终采用post的方式发送。即
```java
@Override
	public String Trans(String from, String targ, String query) throws Exception{
		
		HttpParams params = null;
		params = new HttpPostParams();		//统一采用post，若字符长度小于999用get也可以的
```
或者参考新push的[源码](https://github.com/lsj9383/translate-set/blob/master/src/com/lsj/Trans/GoogleDispatch.java)

**Comment by wzyddg** [comment]
解决了，猜测是俄文字符串在进行URL编码前长度在999之下（例句为408），使程序选择了GET方式，而URL编码后的长度却很长超过了GET请求的最大长度（仅例句编码后为2031）。谢谢作者的帮助。

**Comment by lsj9383** [comment]
不客气。过年了也不休息休息，预祝新年快乐。

**Comment by wzyddg** [comment]
也祝你新年快乐。不过现在因为请求过于频繁触发了人机验证，谷歌接口暂时不让我调了。请问您知道多久才能恢复？以后以多低的频率调用才不会被封吗？

**Comment by lsj9383** [comment]
他怎么提示你的？老实说我还没遇到这个情况，所以也不太清楚。翻译我也只是偶尔用，用的并不频繁。

**Comment by wzyddg** [comment]
返回的结果不是JSON，是这个网页：
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://ipv4.google.com/sorry/index?continue=http://translate.google.cn/translate_a/single&amp;q=EgQBHNl1GOzSncQFIhkA8aeDS_J3iApQHrYv7rXktxUTannflk0WMgNyY24">here</A>.
</BODY></HTML>
点进去链接就让我进行人机验证。没办法了，好像只能等着了。
